### ISSUE TITLE
Spectator mode incompatible with /vanish

### ISSUE THREAD

**Issue by SpaceClouds42** [123456687548/vanish#1]
When I do /vanish, and then go into spectator mode, I am locked in this quasi state between creative and spectator.
I am always in flight mode, I become grayed out, and I can click entities to see from their perspective like I would in spectator mode. But I also see my entire body instead of just my head, I collide with blocks, and when I hit my hotbar hotkeys, the quick teleport buttons don't show up.

**Comment by 123456687548** [comment]
Thanks for reporting the issue, I'm looking into it.

**Comment by 123456687548** [comment]
Found a solution.
