### ISSUE TITLE
Vanished players are still visible when using /list.

### ISSUE THREAD

**Issue by OrangeCatSeth** [123456687548/vanish#2]
![2020-12-09_01 04 41](https://user-images.githubusercontent.com/24788083/101596424-a6cbb380-39ba-11eb-9161-8794a8284cda.png)

**Comment by OrangeCatSeth** [comment]
not sure if i should create another report, but /msg can also be used to reveal a vanished player.

**Comment by 123456687548** [comment]
Thanks for reporting the issue, should be fixed now

**Comment by OrangeCatSeth** [comment]
This needs to be reopened, i see 2 list commands now as a non opped player, /listf hides vanished players, and /list shows them.
I think their function might be swapped, and the permissions don't seem to be fully set up.

**Comment by 123456687548** [comment]
> This isn't fully patched, i see 2 list commands now as a non opped player, /listf hides vanished players, and /list shows them.
> I found a typo on line 19 looking at the source, I corrected it and now it works perfectly.

Noticed that too, was fixed [here](fe337f3980a437cf298377742b6e368cd7dd618e)
