### ISSUE TITLE
Build Failing, Invalid Import

### ISSUE THREAD

**Issue by SpaceClouds42** [123456687548/vanish#25]
It appears that commit [f389330](https://github.com/123456687548/vanish/commit/f3893302ca98d0fca3faedd5db72bbd9250aad7f) started to use an `exeptions` package for `NoTranslateableMessageExeption` used in the `ServerPlayNetworkHandlerMixin`. This package does not exist in the git repo, so my guess is that it was never `git add`ed, causing build fails when people clone the repository.

**Comment by 123456687548** [comment]
a71a05865911d7145df7b61cc941ec4132791c10
