### ISSUE TITLE
The player list on the server screen doesn't work when a player is vanished.

### ISSUE THREAD

**Issue by OrangeCatSeth** [123456687548/vanish#3]
There are 2 players logged in, 1 is vanished in the attached screenshot. It should show the unvanished player's username.
![Screenshot from 2020-12-09 01-57-40](https://user-images.githubusercontent.com/24788083/101601339-32950e00-39c2-11eb-8aa3-e503b58eecc4.png)

**Comment by 123456687548** [comment]
Thanks for reporting the issue, should be fixed now.
