### ISSUE TITLE
Enhancement: /vanish list

### ISSUE THREAD

**Issue by sean-phyx** [123456687548/vanish#40]
Having a command to list the current vanished players would be useful as a config setting or something as when I'm using it I would like to know which admins are in vanish and which are not. 
Obviously this could be done by console however a list command would be kinda nice ;)

Something simple like /vanish list 
and it would list the players that are in vanish.

**Comment by 123456687548** [comment]
Implemented
[Download on Curseforge](https://www.curseforge.com/minecraft/mc-mods/vanish/files/3932852) or [Download on Github](https://github.com/123456687548/vanish/releases/tag/1.19.1_1.4.3)
