### ISSUE TITLE
Players have Default Skin when Vanished

### ISSUE THREAD

**Issue by Luracasmus** [123456687548/vanish#5]
Vanished players have Default Skin after rejoining

Vanished:
![image](https://user-images.githubusercontent.com/60381935/101990483-6d8b9000-3ca7-11eb-8ffa-93cb0149a609.png)

Not vanished:
![image](https://user-images.githubusercontent.com/60381935/101990460-619fce00-3ca7-11eb-9ba1-499fe68a20fa.png)

**Comment by 123456687548** [comment]
What version are you using?
Is it visible for other Players?
For me it doesn't happen.

**Comment by Luracasmus** [comment]
> What version are you using?
> Is it visible for other Players?
> For me it doesn't happen.

Steps to Reproduce

1. Join the server
2. Vanish
3. Leave the server
4. Unvanish

The Tablist name also doesn't reappear after unvanishing.

Other players joining after you have unvanished do not see the Default Skin and they see the name in the Tablist.

Im using Fabric `0.6.1.51` for `Minecraft 1.16.4` with `Velocity 1.1.2` and mods:
```
commandaliases-0.3.0
fabric-api-0.28.0+1.16
FabricProxy-1.3.3
InvView-1.2.0-1.16.2+
lithium-fabric-mc1.16.4-0.6.0
phosphor-fabric-mc1.16.1-0.6.0+build.7
vanish-1.16.4-1.2
worldedit-fabric-mc1.16.3-7.2.1-dist
```

**Comment by 123456687548** [comment]
All done, thanks for reporting
