### ISSUE TITLE
"You're Vanished" Appears in Tab Complete

### ISSUE THREAD

**Issue by ghost** [123456687548/vanish#8]
When vanished "You're Vanished" appears in Tab Complete and spectator teleport

![image](https://user-images.githubusercontent.com/60381935/102806557-63f7db80-43bd-11eb-902d-b317d04f96eb.png)

![image](https://user-images.githubusercontent.com/60381935/102806710-a9b4a400-43bd-11eb-88ed-4555eb0d7595.png)

**Comment by 123456687548** [comment]
I don't think there is anything I can do against that.

**Comment by Luracasmus** [comment]
You could use an action bar instead of a fake player

**Comment by 123456687548** [comment]
Action bars don't stay indefinitely.
If it's not liked, it now can be disabled with #15
